# Generated by Django 3.1 on 2020-12-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20201204_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
