# Generated by Django 3.1 on 2020-12-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20201204_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='discount',
        ),
    ]
