# Generated by Django 3.1 on 2020-09-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200827_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(default=1, max_length=250, verbose_name='Comment'),
            preserve_default=False,
        ),
    ]
